[scan]
Result folder name:  example_emcee
Scan method:       EMCEE
#                  varID  Prior   Min      MAX    Interval  Initial
Input parameters:  x,     flat,   0,       3.14,  20,       1.5
                   y,     flat,   -3.14,   3.14,  20,       1.5
Number of points:  80
Interval of print: 10

[program1]
Program name:    TestFunction
Execute command: ./TestFunction.py
Command path:    utils/
Input file:      1, utils/TestFunction_input.dat
Input variable:  x,       1,      Position, 1,  1
                 y,       1,      Position, 1,  2
Output file:     1, utils/TestFunction_output.dat
Output variable: f,       1,      Position, 1,  2

[constraint]
Gaussian:   f,      1,     0.2

[plot]
Color: x,       y,         f,       test_run_emcee
       x,       y,         Chi2
